[[profile]]
name="home_lyon"
exec = ["notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\""]
  [[profile.output]]
  search = ["m=15B1", "s=0000000000000", "v=HKC OVERSEAS LIMITED"]
  enable = true
  mode = "1920x1080@60"
  position = "13498,10000"
  scale = 1

  [[profile.output]]
  search = "LG Display"
  enable = true
  mode = "1920x1080@60"
  position = "11749,10000"
  scale = 1.1

[[profile]]
name="just_laptop"
exec = ["notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\""]
  [[profile.output]]
  search = "LG Display"
  enable = true
  mode = "1920x1080@60"
  position = "11749,10000"
  scale = 1.1

[[profile]]
name = "work_triple_screen"
exec = ["notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\"", "killall wpaperd", "wpaperd -d"]

  [[profile.output]]
  enable = true
  search = ["m=BenQ GW2490T", "s=39S0050001Q", "v=PNP(BNQ)"]
  # search = ["m=SyncMaster", "s=HMBB405425", "v=Samsung Electric Company"]
  mode = "1920x1080@100Hz"
  position = "7000,9500"
  scale = 1.0
  transform = "90"
  adaptive_sync = false

  [[profile.output]]
  enable = true
  search = ["m=DELL P2317H", "s=HH77Y77JCKPB", "v=Dell Inc."]
  mode = "1920x1080@60Hz"
  position = "8080,10000"
  scale = 1.0
  transform = "normal"
  adaptive_sync = false

  [[profile.output]]
  enable = true
  search = ["m=0x0724", "s=", "v=LG Display"]
  mode = "1920x1080@60.02Hz"
  position = "10000,10400"
  scale = 1.3
  transform = "normal"
  adaptive_sync = false

[[profile]]
name = "home_home"
exec = ["notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\""]

  [[profile.output]]
  enable = true
  search = ["m=0x0724", "s=", "v=LG Display"]
  mode = "1920x1080@60.02Hz"
  position = "11749,10000"
  scale = 1.09765625
  transform = "normal"
  adaptive_sync = false

  [[profile.output]]
  enable = true
  search = ["m=2590G4", "s=0x00007364", "v=PNP(AOC)"]
  mode = "1920x1080@60Hz"
  position = "10789,8920"
  scale = 1.0
  transform = "normal"
  adaptive_sync = false

[[profile]]
name = "generic_HDMI"
exec = ["notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\""]

  [[profile.output]]
  enable = true
  search = "eDP-1"
  mode = "1920x1080@60.02Hz"
  position = "10789,10000"
  scale = 1.09765625
  transform = "normal"
  adaptive_sync = false

  [[profile.output]]
  enable = true
  search = "HDMI-A-1"
  mode = "1920x1080@60Hz"
  position = "8869,10000"
  scale = 1.0
  transform = "normal"
  adaptive_sync = false


[[profile]]
name = "frynis"
exec = ["notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\""]

  [[profile.output]]
  enable = true
  search = ["m=DELL P2419HC", "s=7Y04JQ2", "v=Dell Inc."]
  mode = "1920x1080@60Hz"
  position = "13669,9580"
  scale = 1.0
  transform = "270"
  adaptive_sync = false

  [[profile.output]]
  enable = true
  search = ["m=0x0724", "s=", "v=LG Display"]
  mode = "1920x1080@60.02Hz"
  position = "10000,10000"
  scale = 1.09765625
  transform = "normal"
  adaptive_sync = false

  [[profile.output]]
  enable = true
  search = ["m=HP P22h G5", "s=3CM24801TX", "v=HP Inc."]
  mode = "1920x1080@60Hz"
  position = "11749,10000"
  scale = 1.0
  transform = "normal"
  adaptive_sync = false

[[profile]]
  name = "evas"
exec = ["notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\""]

  [[profile.output]]
  enable = true
  search = ["m=DELL E2216H", "s=2XT7668VDH3B", "v=Dell Inc."]
  mode = "1920x1080@60Hz"
  position = "7909,10000"
  scale = 1.0
  transform = "normal"
  adaptive_sync = false

  [[profile.output]]
  enable = true
  search = ["m=0x0724", "s=", "v=LG Display"]
  mode = "1920x1080@60.02Hz"
  position = "11749,10000"
  scale = 1.09765625
  transform = "normal"
  adaptive_sync = false

  [[profile.output]]
  enable = true
  search = ["m=DELL P2419HC", "s=80L2JQ2", "v=Dell Inc."]
  mode = "1920x1080@60Hz"
  position = "9829,10000"
  scale = 1.0
  transform = "normal"
  adaptive_sync = false

